feat: add score column in spotlighttable
kodadot/rubick pull request #107
Opened 2022-07-03 07:06 UTC by zhengow

**Thank you for your contribution** to the [KodaDot Indexer](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new?

- [ ] PR closes #<issue_number>
- [x] This PR is required for kodadot/nft-gallery#3001

### Before submitting Pull Request, please make sure:

- [ ] My contribution builds **clean without any errors or warnings**
- [ ] I've merged recent default branch -- **main** and I've no conflicts
- [ ] I've tried to respect high code quality standards
- [ ] I've didn't break any original functionality
- [ ] I've posted a screenshot of demonstrated change in this PR

### Optional

- [ ] I've run the indexer and it hasn't failed
- [ ] I've changed schema and performed a migration
- [ ] I found edge cases

### Screenshot

- [ ] My contribution is a **resolver** so I have pic from playground

<img width="2247" alt="image" src="https://user-images.githubusercontent.com/38389586/177029019-ebaf8582-6679-471f-9cb2-d371115f3704.png">
<img width="2186" alt="image" src="https://user-images.githubusercontent.com/38389586/177029041-027504b1-5f65-4364-8948-73fdbe0a0eac.png">

2022-07-03 10:28 UTC, petersopko commented
sorting seems to work, pls check the error :)

2022-07-03 10:31 UTC, petersopko requested changes

2022-07-03 10:31 UTC, petersopko commented on src/server-extension/resolvers/spotlight.ts
> +      console.error("Invalid passionList")
hey, I'm wondering how should this work, I'm passing in various addresses and still ending with "Invalid passionList" in console

2022-07-03 11:10 UTC, vikiival commented
Please be aware that spotlight resolver should not be used.

2022-07-03 11:12 UTC, zhengow commented
> Please be aware that spotlight resolver should not be used.

why is it?

2022-07-03 11:19 UTC, vikiival commented
> why is it?


we should be using the cached version of it.  

Please see:
https://github.com/kodadot/rubick/blob/4579f5007f92e8debf8dd579a83fe37691ded1dd/src/mappings/utils/cache.ts

2022-07-03 17:31 UTC, zhengow commented
> > why is it?
> 
> we should be using the cached version of it.
> 
> Please see: https://github.com/kodadot/rubick/blob/4579f5007f92e8debf8dd579a83fe37691ded1dd/src/mappings/utils/cache.ts

done. Do I need to commit generated files: `src/model/generated/spotlight.model.ts` and `db/migrations/1656868613783-Data.js`
<img width="1370" alt="image" src="https://user-images.githubusercontent.com/38389586/177050863-b8dba63a-ab29-4af6-a702-2190800e2efd.png">

2022-07-06 07:36 UTC, petersopko commented
> > we should be using the cached version of it.
> > Please see: https://github.com/kodadot/rubick/blob/4579f5007f92e8debf8dd579a83fe37691ded1dd/src/mappings/utils/cache.ts
> 
> Done. Do I need to commit generated files: `src/model/generated/spotlight.model.ts` and `db/migrations/1656868613783-Data.js` ?

I've done the testing, this wfm, can't give a definite answer about the generated files here, my guess is yes, so the migration doesn't have to be done every time in the future, @vikiival can you please help here?

2022-07-06 07:36 UTC, petersopko approved these changes

2022-07-06 08:56 UTC, petersopko requested changes
ok, after discussing this, you need to commit the generated files as well, in order to have the migration recorded in the repo

2022-07-06 08:57 UTC, petersopko commented
@zhengow that one last thing and it's good to go :)

2022-07-06 09:19 UTC, zhengow commented
> @zhengow that one last thing and it's good to go :)

great! Already commit files.😀

2022-07-08 06:36 UTC, zhengow commented
> @zhengow that one last thing and it's good to go :)

When can we merge and move on🙌

2022-07-08 08:10 UTC, vikiival requested changes
smol stuff

2022-07-08 08:10 UTC, vikiival commented on src/mappings/utils/cache.ts
> +        SUM(CASE WHEN ne.issuer <> ne.current_owner THEN 1 ELSE 0 END) * COUNT(distinct meta_id) / COUNT(*) as score
Please do not use `*` 

It's not performant wise

2022-07-17 02:15 UTC, zhengow commented
Hi， @vikiival 🤲
Cloud you pls check thid？

2022-07-18 08:54 UTC, vikiival commented
> Cloud you pls check this？

sir there is a unresolved comment

2022-07-18 10:24 UTC, zhengow commented
> > Cloud you pls check this？
> 
> sir there is a unresolved comment

Already change `count(*)` to `count(1)`, how about now?

2022-07-28 13:48 UTC, zhengow commented
@vikiival Do u have time to check this👀

2022-07-28 14:16 UTC, vikiival requested changes

2022-07-28 14:16 UTC, vikiival commented on schema.graphql
> +  score: Float!
Please remove `!`

2022-07-28 18:54 UTC, vikiival requested changes
https://github.com/kodadot/rubick#development-flow

2022-07-28 19:20 UTC, zhengow commented
Sorry I forget this. First time to make PR for db. Already done `codegen` work.
How about add `codegen` command in husky that everyone can avoid this 👀

2022-07-28 19:22 UTC, vikiival commented
> How about add codegen command in husky that everyone can avoid this

Feel free to make a PR love to have that!

2022-07-28 19:24 UTC, zhengow commented
Let me check this later👌






------------------ Original ------------------
From: Viki Val ***@***.***&gt;
Date: Fri,Jul 29,2022 3:23 AM
To: kodadot/rubick ***@***.***&gt;
Cc: zhengow ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [kodadot/rubick] feat: add score column in spotlighttable (PR#107)





  
How about add codegen command in husky that everyone can avoid this
  
Feel free to make a PR love to have that!
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

2022-07-29 09:58 UTC, vikiival commented
Last thing you are missing is to update the migration and I think we are good to go

2022-07-29 17:15 UTC, zhengow commented
> Last thing you are missing is to update the migration and I think we are good to go

The step to doing is:
1. checkout to branch `main`
2. `just up` to start db
3. `just reset` to init db
4. checkout to my branch
5. `just update-db` to get migration file

Am I right?
However, it seem that the file that I get is just the same as [4578a](https://github.com/kodadot/rubick/pull/107/commits/4578a4219a969e63c095499ebe2350964512227e)

2022-08-12 13:23 UTC, petersopko commented
@zhengow this one might be helpful? https://medium.com/kodadot/index-your-kusama-nfts-b4fab5ae1628

2022-08-12 18:32 UTC, zhengow commented
> Last thing you are missing is to update the migration and I think we are good to go

update migration file, remove `not null` words manually. Now is it correct?
But why the automatic generated file has `not null` filed? 👀

2022-10-18 12:48 UTC, vikiival commented
The PR looks legit can you please run it again to be sure that everything works?

2023-09-28 11:24 UTC, vikiival commented
Closing as obsolete, thanks for the contribution

2023-09-28 11:24 UTC, closed without merging