1619 flipping nfts
kodadot/rubick pull request #88
Opened 2022-05-23 08:22 UTC by KngZhi

- feat: model of flipping nft
- feat: resolver

2022-05-23 09:45 UTC, vikiival requested changes

2022-05-23 09:45 UTC, vikiival commented on src/server-extension/query/nft.ts
> +export const flippingQuery = `select
Please use the correct SQL formating
- KEYWORDS UPPERCASE (SELECT, FROM, GROUP BY)
- and formatiing (use some online formatter)

2022-05-23 09:45 UTC, vikiival commented on src/server-extension/query/nft.ts
> +limit 20`
make as parameter

2022-05-24 06:38 UTC, vikiival reviewed
noice

2022-05-27 06:46 UTC, KngZhi commented
https://github.com/kodadot/nft-gallery/issues/1115

2022-05-27 11:25 UTC, vikiival requested changes

2022-05-27 11:25 UTC, vikiival commented on src/server-extension/resolvers/flippingNfts.ts
> +type previousNft = {
Type with UpperCase pls

2022-05-27 11:26 UTC, vikiival commented
As I have nothing specific for this PR. 
I honestly think that this should be cached the same way as spotlight or series.

The computation on the DB is overkill.
I can spawn @eldargab

2022-05-28 14:53 UTC, eldargab commented
I'm lacking context here. Generally plain database queries are of course better unless it becomes expensive.
May be  @ma-shulgin can provide a better input.

2022-05-30 03:42 UTC, KngZhi commented on src/server-extension/model/nft.model.ts
> +export class FlippingNFT {
Maybe I should change all those `Flipping` to `MostTraded`?

2022-05-31 09:20 UTC, vikiival commented
Hey @KngZhi we had some issues with a subsquid node that was unable to process. With your PR I have a feeling that we can buy a ⚰️ for the processor.


What are the next steps: 
- It can't go out as a resolver. 
- so preferrably I would make a caching and a new entity (similar stuff what has been done in #87)

2022-06-02 06:22 UTC, KngZhi commented
Hey @vikiival, after I checked with #87 I kind of feel it is unable to do so.

Some fields have relied on the previous query results, there are two sequence queries.

2022-06-02 06:23 UTC, KngZhi commented
> Hey @vikiival, after I checked with #87 I kind of feel it is unable to do so.
> 
> Some fields have relied on the previous query results, there are two sequenced queries.

2022-06-14 09:35 UTC, petersopko commented
@KngZhi what's the status of this PR? we have now two PRs (this one and https://github.com/kodadot/nft-gallery/pull/3063) which are 3 weeks old and still open 😢

2022-06-14 11:22 UTC, vikiival commented
I wont merge this as resolver. 

We are already running out of memory and this is simply overkill

2022-07-06 10:19 UTC, petersopko commented
based on @vikiival comments, my understanding here is that this should be done as extension of `cache.ts` not as separate resolvers. let's close this one since it's sitting here for a while, and reopen with extended cache whenever you feel ready to do that @KngZhi

2022-07-06 10:19 UTC, closed without merging