feat: last event resolver
kodadot/rubick pull request #89
Opened 2022-05-25 05:34 UTC by Jarsen136

WFM

<img width="937" alt="image" src="https://user-images.githubusercontent.com/31397967/170187349-606e101e-f2b1-4f6b-bb7c-f1829a6653ca.png">

ref:
#29 
https://github.com/kodadot/nft-gallery/issues/3059

2022-05-26 23:49 UTC, Jarsen136 commented
This PR seems conflict with https://github.com/kodadot/rubick/pull/76 : )
cc @vikiival

2022-05-26 23:49 UTC, Jarsen136 commented
This PR seems conflict with https://github.com/kodadot/rubick/pull/76 : )
cc @vikiival

2022-05-31 06:44 UTC, roiLeo reviewed
would be cool to have interaction from `lastListEventQuery` as a param so we can do the same for 'BUY'

It also lacks the possibility of sorting

2022-05-31 09:03 UTC, vikiival requested changes

2022-05-31 09:03 UTC, vikiival commented on src/server-extension/resolvers/event.ts
> +  async genericEventQuery(query: string): Promise<LastEventEntity[]> {
use makeQuery pls

2022-05-31 09:03 UTC, vikiival commented on src/server-extension/query/event.ts
> +LIMIT ${limit} OFFSET ${offset}`
```suggestion
LIMIT $1 OFFSET $2`
```

2022-05-31 09:03 UTC, vikiival commented on src/server-extension/resolvers/event.ts
> +    @Arg('offset', { nullable: true }) offset: number,
add default to 0

2022-05-31 09:03 UTC, vikiival commented on src/server-extension/resolvers/event.ts
> +    @Arg('limit', { nullable: true }) limit: number,
add default to 20

2022-05-31 09:04 UTC, vikiival commented on src/server-extension/model/event.model.ts
> +  meta!: String
should be named `value`

2022-05-31 15:19 UTC, Jarsen136 commented
> It also lacks the possibility of sorting

Maybe it should sort by timestamp by default because it was named `lastEvent`

2022-05-31 15:28 UTC, Jarsen136 commented on src/server-extension/model/event.model.ts
> +  meta!: String
: )

2022-05-31 16:00 UTC, vikiival commented on src/server-extension/query/event.ts
> +    and ne.burned = false
```suggestion
    AND ne.burned = false
```

2022-06-07 23:48 UTC, Jarsen136 commented
How about merging this pull request and deploying it ? 👀

2022-06-11 13:26 UTC, vikiival approved these changes

2022-06-11 13:26 UTC, merged

2022-06-11 13:27 UTC, vikiival commented
> How about merging this pull request and deploying it ? 👀

Sorry, we've been busy with the dotsama prague