feat: resolver on hotdashboard
kodadot/rubick pull request #96
Opened 2022-06-09 16:43 UTC by KngZhi

hot dashboard resolver on stats page.

ref: https://github.com/kodadot/nft-gallery/issues/3114

![image](https://user-images.githubusercontent.com/11361147/173210979-c7d29f25-713b-4c93-b14d-830893add0fd.png)

2022-06-11 13:24 UTC, vikiival commented
<img width="123" alt="Screenshot 2022-06-11 at 15 24 46" src="https://user-images.githubusercontent.com/22471030/173189843-22da88cb-93b8-4813-a21a-772dd7289dec.png">
this does not look safe

2022-06-11 13:25 UTC, vikiival commented
Plase also add screenshot from the playground

2022-06-12 07:29 UTC, KngZhi commented
> Plase also add screenshot from the playground

Okay, updated. :)

2022-06-13 18:16 UTC, vikiival requested changes

2022-06-15 13:38 UTC, KngZhi commented on src/server-extension/query/nft.ts
> +    AND e."timestamp" >= NOW() - INTERVAL '${dateRange}'
for `$1` or `'$1'`, both would raise errors.

![image](https://user-images.githubusercontent.com/11361147/173840617-2337a5ae-5fa8-48f0-9295-e0e64d6eeada.png)

2022-10-18 12:44 UTC, vikiival requested changes
Smol stuff

2022-10-18 12:44 UTC, vikiival commented on src/server-extension/query/nft.ts
> +ORDER BY e.timestamp desc`
```suggestion
ORDER BY e.timestamp DESC`
```

2022-10-18 12:48 UTC, vikiival commented
<img width="331" alt="Screenshot 2022-10-18 at 14 48 24" src="https://user-images.githubusercontent.com/22471030/196433738-0d169ad3-0390-420f-8fd8-07eb48a72097.png">

2022-10-18 14:09 UTC, vikiival approved these changes

2022-10-18 14:09 UTC, merged